### ISSUE TITLE
Support JWT tokens with multi-valued audience claim

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-oauth.java#26]
See [RFC 7519, section 4.1.3 "aud" (Audience) claim](https://tools.ietf.org/html/rfc7519#section-4.1.3).

The `RESOLVE` command should continue to support only one audience, but during JWT token processing, we need to check if _any_ of the audience values presented in the token match the audience required during `RESOLVE`.

**Comment by dknoma** [comment]
added functionality for tokens containing multiple audiences. `"aud"` claims are now space-delimited Strings rather than a single string. ex. `"aud1 aud2 aud3"` instead of `"test aud"` which would've been a single audience String originally.

**Comment by jfallows** [comment]
Fixed by #28
