### ISSUE TITLE
Avoid hard fail if keys file is not found

### ISSUE THREAD

**Issue by cmebarrow** [reaktivity/nukleus-oauth.java#3]
Currently the auth-jwt nukleus will not start up if the keys file is not found. The name of that file is given by system property `auth.jwt.keys` and defaults to `keys.jwk`. Instead of failing with an exception on startup we should allow the file not to be found and only give an error if a route command is processed specifying a non-zero value for authorization (which would imply token verification is required). If such a route command is processed an ERROR frame should result. We *could* also throw an exception to make the cause more obvious.

**Comment by jfallows** [comment]
Now fixed.
